### ISSUE TITLE
Seems to work also with internal url's

### ISSUE THREAD

**Issue by vandalon** [jjlawren/sonos_cloud#1]
Ola, thanks for this! It seems that internal url's also work :) I have nothing open to the outside world and it still just works :)

**Comment by jjlawren** [comment]
Interesting, that was not my experience in my testing. I'll test some more when I have time and update the docs if I can find a pattern. 👍

**Comment by vandalon** [comment]
It only works with https and a valid cert as far as I can tell.

**Comment by jjlawren** [comment]
Local HTTP by IP address still does not work for me (e.g., `http://192.168.1.20:8123/local/sound_clips/doorbell.mp3`). Same with local HTTP against a resolvable domain name.

Additionally, local HTTPS is not working against my HA host, but there are several possible reasons for that:
1. Wildcard certificates are not accepted (e.g., `*.domain.com` instead of an explicit `ha.domain.com` subdomain)
2. Split DNS. Names resolve to a local IP within my network and a public one externally. 
3. Let's Encrypt certificates are not accepted. I don't believe this is true as they're cross-signed by `DST Root CA X3` which is listed as an included root cert [here](https://developer.sonos.com/build/content-service-get-started/security/#Certificate-authorities-trusted-by-Sonos-players).

So I'm still not clear on where it's failing. I'm sniffing the DNS requests made by the speaker and confirm it's receiving the proper IP, so it must be something related to the certificates or other local IP restriction.

@vandalon any chance your internal URL is resolving to your public IP which your router sends back to the local box via hairpin NAT or something similar?

**Comment by jjlawren** [comment]
Well, I feel like an idiot. I forgot to open up the firewall between my Sonos speakers and my HA instance. All my various tests are working just fine now. 🤦 

Thanks again for testing and letting me know that all worked fine.

**Comment by Rodiii** [comment]
Hi @vandalon, This sounds interesting. Could you give me some hints how I can setup local https with a valid cert? I'm having a hassio installation.

**Comment by vandalon** [comment]
@Rodiii use the lets encrypt addon :)

**Comment by Rodiii** [comment]
I just made the plugin working with duckdns + opening port + setting the internal and external url within home assistant.
Anyhow, as soon as I comment out the external URL tts via media_source stops working.

Probably this is because the certificate is created for the external and not internal url, right? => certification check fails for sonos.

How are you solving this issue?

**Comment by Rodiii** [comment]
Just made it. For others who want to achieve this:
1. Make sonos_cloud running with the external URL (1. install duckdns addon 2. create duckdns account 3. configure duckdns addon 4. create port forwarding in your home router 5. set internal and external urls in home assistant configuration)
2. Check if sonos_cloud works
3. Remove port forwarding from router
4. Install avguard addon for home assistant (you have to restart home assistant to get it working properly)
5. Configure your router dns server to the homeassistant avguard dns server (please follow avguard tutorials for this)
6. Check if avguard dns server is working by checking the statistics in avguard
7. Create dns_rewrite rule in avguard to let your external duckdns homeassistant url to be resolved with your internal IP
8. Configure your router that this URL is safe to be routed to an internal IP (DNS-Rebind-Protection whitelist)
9. Check if you can access home assistant with the duckdns URL (with no port forwarding enabled in your router)
10. Check if sonos_cloud still works
